name: "Terraform"

on: 
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v1

    - name: Run a Terraform init  
      uses: docker://hashicorp/terraform:latest
      with:
        entrypoint: terraform
        args: init

    - name: Run a Terraform validate    
      uses: docker://hashicorp/terraform:latest
      with:
        entrypoint: terraform
        args: validate
        
    - name: Run a Terraform format check    
      uses: docker://hashicorp/terraform:latest
      with:
        entrypoint: terraform
        args: fmt -check

    - name: Send slack notification
      uses: 8398a7/action-slack@v3
      with: 
        status: ${{ job.status }}
        fields: repo,message,commit,author,eventName,ref,workflow,job,took
      env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()